INSERT INTO recipe_group (id,name) VALUES (9,'Hiba')
INSERT INTO recipe_group (id,name) VALUES (40,'Hiba2')
INSERT INTO recipe_group (id,name) VALUES (42,'Húsos levesek')
INSERT INTO recipe_group (id,name) VALUES (43,'Egyéb levesek')
INSERT INTO recipe_group (id,name) VALUES (44,'Levesbetétek')
INSERT INTO recipe_group (id,name) VALUES (45,'Sűrített főzelékek')
INSERT INTO recipe_group (id,name) VALUES (46,'Sűrítetlen főzelékek')
INSERT INTO recipe_group (id,name) VALUES (47,'Rakott- és töltött zöldség-főzelékfélék')
INSERT INTO recipe_group (id,name) VALUES (48,'Burgonyaalapú köretek')
INSERT INTO recipe_group (id,name) VALUES (49,'Rizs- és gabonaalapú köretek')
INSERT INTO recipe_group (id,name) VALUES (50,'Tésztaalapú köretek')
INSERT INTO recipe_group (id,name) VALUES (51,'Mártásos saláták, hidegkonyhai készítmények')
INSERT INTO recipe_group (id,name) VALUES (52,'Ecetes- és pácnélküli saláták')
INSERT INTO recipe_group (id,name) VALUES (53,'Hideg mártások')
INSERT INTO recipe_group (id,name) VALUES (54,'Meleg mártások')
INSERT INTO recipe_group (id,name) VALUES (55,'Egytálételek')
INSERT INTO recipe_group (id,name) VALUES (56,'Húspótlók')
INSERT INTO recipe_group (id,name) VALUES (57,'Tojásételek')
INSERT INTO recipe_group (id,name) VALUES (58,'Szárnyashúsból készült húsételek')
INSERT INTO recipe_group (id,name) VALUES (59,'Sertéshúsból készült húsételek')
INSERT INTO recipe_group (id,name) VALUES (60,'Marhahúsból készült húsételek')
INSERT INTO recipe_group (id,name) VALUES (61,'Halból készült ételek')
INSERT INTO recipe_group (id,name) VALUES (62,'Egyéb húsételek')
INSERT INTO recipe_group (id,name) VALUES (63,'Belsőségből készült ételek')
INSERT INTO recipe_group (id,name) VALUES (64,'Főtt tészták')
INSERT INTO recipe_group (id,name) VALUES (65,'Sült tészták')
INSERT INTO recipe_group (id,name) VALUES (66,'Tejes ételek')
INSERT INTO recipe_group (id,name) VALUES (67,'Sütemények, egyéb édességek')
INSERT INTO recipe_group (id,name) VALUES (68,'Turmixok, egyéb italok')
INSERT INTO recipe_group (id,name) VALUES (69,'Szendvicskrémek')
INSERT INTO recipe_group (id,name) VALUES (70,'Szendvicsek, fast foods')
INSERT INTO recipe_group (id,name) VALUES (71,'Diabetikus ételek')
INSERT INTO recipe_group (id,name) VALUES (72,'Zsírszegény ételek')
INSERT INTO recipe_group (id,name) VALUES (73,'Egyéb diétás ételek')
INSERT INTO recipe_group (id,name) VALUES (74,'Vegetáriánus ételek')
INSERT INTO recipe_group (id,name) VALUES (75,'Egyéb ételek')
INSERT INTO recipe_group (id,name) VALUES (76,'Táplálékkiegészítők')
INSERT INTO recipe_group (id,name) VALUES (77,'Ásványvizek')
INSERT INTO recipe_group (id,name) VALUES (78,'Bébiételek')
INSERT INTO recipe_group (id,name) VALUES (79,'Tápszerek')

INSERT INTO material_group (id,name) VALUES (1,'Gabonamagvak, őrlemények, keményítők')
INSERT INTO material_group (id,name) VALUES (2,'Hüvelyesek és termékeik')
INSERT INTO material_group (id,name) VALUES (3,'Száraztészták')
INSERT INTO material_group (id,name) VALUES (4,'Péksütemények')
INSERT INTO material_group (id,name) VALUES (5,'Fehér kenyerek')
INSERT INTO material_group (id,name) VALUES (6,'Barna kenyerek')
INSERT INTO material_group (id,name) VALUES (7,'Tejek, tejes italok')
INSERT INTO material_group (id,name) VALUES (8,'Savanyított tejtermékek')
INSERT INTO material_group (id,name) VALUES (9,'Túrók, túrókészítmények')
INSERT INTO material_group (id,name) VALUES (10,'Sajtok')
INSERT INTO material_group (id,name) VALUES (11,'Egyéb tejkészítmények')
INSERT INTO material_group (id,name) VALUES (12,'Tojások')
INSERT INTO material_group (id,name) VALUES (13,'Baromfi húsok')
INSERT INTO material_group (id,name) VALUES (14,'Sertés húsok')
INSERT INTO material_group (id,name) VALUES (15,'Marha húsok')
INSERT INTO material_group (id,name) VALUES (16,'Halak')
INSERT INTO material_group (id,name) VALUES (17,'Egyéb húsok')
INSERT INTO material_group (id,name) VALUES (18,'Belsőségek, -készítmények, -konzervek')
INSERT INTO material_group (id,name) VALUES (19,'Húskészítmények')
INSERT INTO material_group (id,name) VALUES (20,'Hús-, húskészítmény konzerv')
INSERT INTO material_group (id,name) VALUES (21,'Halkonzervek, tengeri termékek')
INSERT INTO material_group (id,name) VALUES (22,'Állati zsiradékok')
INSERT INTO material_group (id,name) VALUES (23,'Növényi zsiradékok')
INSERT INTO material_group (id,name) VALUES (24,'Burgonya')
INSERT INTO material_group (id,name) VALUES (25,'Friss és fagyasztott zöldségek, főzelékek')
INSERT INTO material_group (id,name) VALUES (26,'Zöldség-, főzelékkészítmények, konzervek')
INSERT INTO material_group (id,name) VALUES (27,'Gombák')
INSERT INTO material_group (id,name) VALUES (28,'Friss és fagyasztott gyümölcsök')
INSERT INTO material_group (id,name) VALUES (29,'Befőttek, gyümölcskészítmények')
INSERT INTO material_group (id,name) VALUES (30,'Lekvárok')
INSERT INTO material_group (id,name) VALUES (31,'Diófélék, olajosmagvak')
INSERT INTO material_group (id,name) VALUES (32,'Cukor, méz')
INSERT INTO material_group (id,name) VALUES (33,'Ételízesítők')
INSERT INTO material_group (id,name) VALUES (34,'Sütő-, és édesipari termékek')
INSERT INTO material_group (id,name) VALUES (35,'Jégkrémek, fagylaltok')
INSERT INTO material_group (id,name) VALUES (36,'Égetett szeszesitalok')
INSERT INTO material_group (id,name) VALUES (37,'Borfélék')
INSERT INTO material_group (id,name) VALUES (38,'Sörök')
INSERT INTO material_group (id,name) VALUES (39,'Szénsavas üdítők, szörpök')
INSERT INTO material_group (id,name) VALUES (40,'Gyümölcslevek, zöldséglevek')
INSERT INTO material_group (id,name) VALUES (41,'Egyéb nyersanyagok')
INSERT INTO material_group (id,name) VALUES (76,'Táplálékkiegészítők')
INSERT INTO material_group (id,name) VALUES (77,'Ásványvizek')



INSERT INTO doses (id,name) VALUES (1,'adag')
INSERT INTO doses (id,name) VALUES (2,'darab')
INSERT INTO doses (id,name) VALUES (3,'100 g')


INSERT INTO units (id,name) VALUES (1,'g')
INSERT INTO units (id,name) VALUES (2,'dkg')
INSERT INTO units (id,name) VALUES (3,'kg')
INSERT INTO units (id,name) VALUES (4,'ml')
INSERT INTO units (id,name) VALUES (5,'dl')
INSERT INTO units (id,name) VALUES (6,'l')
INSERT INTO units (id,name) VALUES (7,'db')
INSERT INTO units (id,name) VALUES (8,'mokkásk.')
INSERT INTO units (id,name) VALUES (9,'kiskanál')
INSERT INTO units (id,name) VALUES (10,'evőkanál')
INSERT INTO units (id,name) VALUES (11,'merők.')
INSERT INTO units (id,name) VALUES (12,'n.darab')
INSERT INTO units (id,name) VALUES (13,'kö.darab')
INSERT INTO units (id,name) VALUES (14,'k.darab')
INSERT INTO units (id,name) VALUES (15,'n.szelet')
INSERT INTO units (id,name) VALUES (16,'kö.szelet')
INSERT INTO units (id,name) VALUES (17,'k.szelet')
INSERT INTO units (id,name) VALUES (18,'p.mokkásk.')
INSERT INTO units (id,name) VALUES (19,'kö.mokkásk.')
INSERT INTO units (id,name) VALUES (20,'cs.mokkásk.')
INSERT INTO units (id,name) VALUES (21,'p.kiskanál')
INSERT INTO units (id,name) VALUES (22,'kö.kiskanál')
INSERT INTO units (id,name) VALUES (23,'cs.kiskanál')
INSERT INTO units (id,name) VALUES (24,'p.evőkanál')
INSERT INTO units (id,name) VALUES (25,'kö.evőkanál')
INSERT INTO units (id,name) VALUES (26,'cs.evőkanál')
INSERT INTO units (id,name) VALUES (27,'p.merők.')
INSERT INTO units (id,name) VALUES (28,'kö.merők.')
INSERT INTO units (id,name) VALUES (29,'cs.merők.')
INSERT INTO units (id,name) VALUES (30,'kompótostál')
INSERT INTO units (id,name) VALUES (31,'bögre')
INSERT INTO units (id,name) VALUES (32,'pohár')
INSERT INTO units (id,name) VALUES (33,'nagy fej')
INSERT INTO units (id,name) VALUES (34,'kö.fej')
INSERT INTO units (id,name) VALUES (35,'kis fej')
INSERT INTO units (id,name) VALUES (36,'nagy fürt')
INSERT INTO units (id,name) VALUES (37,'kö.fürt')
INSERT INTO units (id,name) VALUES (38,'kis fürt')
INSERT INTO units (id,name) VALUES (39,'csomag')
INSERT INTO units (id,name) VALUES (40,'gerezd')
INSERT INTO units (id,name) VALUES (41,'adag')


INSERT INTO nutrients (id,name,abbreviation,unit) VALUES (1,'Energia','Oenerg','kJ')
INSERT INTO nutrients (id,name,abbreviation,unit) VALUES (2,'Fehérje','Ofeh','g')
INSERT INTO nutrients (id,name,abbreviation,unit) VALUES (25,'Zsír','Ozsir','g')
INSERT INTO nutrients (id,name,abbreviation,unit) VALUES (50,'Koleszterin','Chol','mg')
INSERT INTO nutrients (id,name,abbreviation,unit) VALUES (51,'Szénhidrát','COH','g')
INSERT INTO nutrients (id,name,abbreviation,unit) VALUES (55,'Élelmi rost','Elrost','g')
INSERT INTO nutrients (id,name,abbreviation,unit) VALUES (60,'Nátrium','Na','mg')
INSERT INTO nutrients (id,name,abbreviation,unit) VALUES (61,'Kálium','K','mg')
INSERT INTO nutrients (id,name,abbreviation,unit) VALUES (62,'Kalcium','Ca','mg')
INSERT INTO nutrients (id,name,abbreviation,unit) VALUES (63,'Magnézium','Mg','mg')
INSERT INTO nutrients (id,name,abbreviation,unit) VALUES (64,'Vas','Fe','mg')
INSERT INTO nutrients (id,name,abbreviation,unit) VALUES (66,'Cink','Zn','mg')
INSERT INTO nutrients (id,name,abbreviation,unit) VALUES (69,'Foszfor','P','mg')
INSERT INTO nutrients (id,name,abbreviation,unit) VALUES (77,'Retinol ekv.','Retekv','mg')
INSERT INTO nutrients (id,name,abbreviation,unit) VALUES (78,'B1-vitamin','B1','µg')
INSERT INTO nutrients (id,name,abbreviation,unit) VALUES (79,'B2-vitamin','B2','µg')
INSERT INTO nutrients (id,name,abbreviation,unit) VALUES (80,'B6-vitamin','B6','µg')
INSERT INTO nutrients (id,name,abbreviation,unit) VALUES (81,'B12-vitamin','B12','µg')
INSERT INTO nutrients (id,name,abbreviation,unit) VALUES (82,'C-vitamin','C','mg')
INSERT INTO nutrients (id,name,abbreviation,unit) VALUES (83,'D-vitamin','D','µg')
INSERT INTO nutrients (id,name,abbreviation,unit) VALUES (84,'E-vitamin','E','mg')
INSERT INTO nutrients (id,name,abbreviation,unit) VALUES (86,'Niacin ekv.','Niaekv','mg')
INSERT INTO nutrients (id,name,abbreviation,unit) VALUES (87,'Folsav','Fols','µg')


INSERT INTO RECIPES (id,name,dose_id,recipegroup_id,preparation) VALUES (2016,'körözött juhtúróból, vajjal',3,9,'A túrót áttörjük, hozzáadjuk az apróra vágott vöröshagymát, a tejfölt, a vajat és a fűszereket, majd jól kikeverjük.')
INSERT INTO RECIPES (id,name,dose_id,recipegroup_id,preparation) VALUES (18514,'Túrókrém, eperlekvárral',1,9,'A túrót elkeverjük a joghurttal, majd a lekvárral ízesítjük.')
INSERT INTO RECIPES (id,name,dose_id,recipegroup_id,preparation) VALUES (18307,'Limonádé, édesítőszerrel',1,40,'A citrom kifacsart levét belekeverjük a vízbe, édesítőszerrel ízesítjük, tetszés szerinti hőmérsékleten kínáljuk.')
INSERT INTO RECIPES (id,name,dose_id,recipegroup_id,preparation) VALUES (4301,'Kassai burgonyaleves',1,42,'Az olajon üvegesre pároljuk a hagymát. Rátesszük a kockákra vágott húst, ízesítjük sóval, borssal, fűszerpaprikával, átpirítjuk, majd hozzátesszük a tisztított, megmosott apróra vágott vegyes zöldséget, valamint az apróra vágott petrezselymet. Felengedjük kevés vízzel, és fedő alatt pároljuk. Amikor már majdnem kész, felöntjük megfelelő mennyiségű vízzel, és beletesszük a megtisztított, megmosott, apró kockákra vágott burgonyát. Készre főzzük, szükség szerint utóízesítjük, legvégül pedig hozzámelegítjük, és belecsorgatjuk a tejfölt.')
INSERT INTO RECIPES (id,name,dose_id,recipegroup_id,preparation) VALUES (4307,'Tárkonyos pulykaraguleves',1,42,'Az olajon üvegesre pároljuk a hagymát. Rátesszük a kockákra vágott húst, ízesítjük sóval, petrezselyemzölddel, tárkonnyal. Átpirítjuk, majd hozzátesszük a tisztított, megmosott apróra vágott vegyes zöldségeket, valamint az apróra vágott petrezselymet. Felengedjük kevés vízzel, és fedő alatt pároljuk. Többször visszapótoljuk az elpárolgott vizet, majd amikor a hús és a zöldségek is megpuhultak, felengedjük a megfelelő mennyiségű vízzel. A tejfölös habarást óvatosan hozzámelegítjük, majd alaposan átforraljuk, utóízesítjük citromlével, petrezselyemzölddel.')
INSERT INTO RECIPES (id,name,dose_id,recipegroup_id,preparation) VALUES (4566,'Kolbászos burgonyaleves',1,42,'A felhevített olajon aranysárgára pirítjuk az apróra vágott hagymát. Hozzátesszük a kockára vágott főtt sonkát és a vékonyra szeletelt kolbászt, és időnként megkeverve pirítjuk meg 5 percig. Hozzáadjuk a káposztát, a burgonyát és a marhahúsleves alapot és a köményt. Fűszerezzük borssal és forraljuk fel. Közepes lángon a levest főzzük addig, amíg a burgonya puha nem lesz. A kész levest forrón, apróra vágott újhagymával díszítve tálaljuk.')
INSERT INTO RECIPES (id,name,dose_id,recipegroup_id,preparation) VALUES (9502,'Csirkehúsleves',1,42,'A csirkét megmossuk, feldaraboljuk, és megfelelő mennyiségű hideg vízben feltesszük főni. Ügyeljünk rá, hogy megfelelő mennyiségű legyen a víz, mert később a vizet már nem célszerű pótolni, hiszen így könnyen zavarossá válhat a leves. Amikor elkezd forrni a tüzet a legkisebbre vesszük, ízesítjük egészben hagyott hagymával, fokhagymával, szemes borssal. Kb. háromnegyed órányi forralás után beletesszük a megtisztított, kisebb darabokra vágott zöldségeket, a sót és a fűszereket. Újraforrástól számítva, még kb. fél órát főzzük, majd félrehúzzuk, illetve lekapcsoljuk, és hagyjuk ülepedni. A főtt csirkehúst a levesben vagy a leves mellé tálaljuk.')
INSERT INTO RECIPES (id,name,dose_id,recipegroup_id,preparation) VALUES (9503,'Sertéshúsleves',1,42,'A sertéshúst megmossuk és megfelelő mennyiségű hideg vízben feltesszük főni. Ügyeljünk rá, hogy megfelelő mennyiségű legyen a víz, mert később a vizet már nem célszerű pótolni, hiszen így könnyen zavarossá válhat a leves. Amikor elkezd forrni a tüzet a legkisebbre vesszük, ízesítjük egészben hagyott hagymával, fokhagymával, szemes borssal. Kb. egy órányi forralás után beletesszük a megtisztított, kisebb darabokra vágott zöldségeket, a sót és a fűszereket. Újraforrástól számítva, még kb. fél órát főzzük, majd félrehúzzuk, illetve lekapcsoljuk, és hagyjuk ülepedni, majd leszűrjük. A főtt húst a rostjaira merőlegesen felszeleteljük és a levesben vagy a leves mellé tálaljuk.')
INSERT INTO RECIPES (id,name,dose_id,recipegroup_id,preparation) VALUES (9504,'Marhahúsleves',1,42,'A marhahúst megmossuk és megfelelő mennyiségű hideg vízben feltesszük főni. Ügyeljünk rá, hogy megfelelő mennyiségű legyen a víz, mert később a vizet már nem célszerű pótolni, hiszen így könnyen zavarossá válhat a leves. Amikor elkezd forrni a tüzet a legkisebbre vesszük, ízesítjük egészben hagyott hagymával, fokhagymával, szemes borssal. Kb. egy órányi forralás után beletesszük a megtisztított, kisebb darabokra vágott zöldségeket, a sót és a fűszereket. Újraforrástól számítva, még kb. fél órát főzzük, majd félrehúzzuk, illetve lekapcsoljuk, és hagyjuk ülepedni, majd leszűrjük. A főtt húst a rostjaira merőlegesen felszeleteljük és a levesben vagy a leves mellé tálaljuk.')
INSERT INTO RECIPES (id,name,dose_id,recipegroup_id,preparation) VALUES (9505,'Húsgombóc leves',1,42,'A sertéshúst megmossuk, ledaráljuk. Hozzáadjuk a beáztatott, kicsavart zsemlét. (Ezzel együtt is darálhatjuk a húst.) Ízesítjük sóval, őrölt borssal, apróra vágott petrezselyemmel, valamint egy kevés aprított vöröshagymával. Beletesszük a tojást, és szükség szerint zsemlemorzsát. Alaposan összedolgozzuk, egy tálcára gombócokat formázunk belőle, majd félretesszük.
 Az olajon megpirítjuk a vöröshagyma maradékát, rátesszük a megtisztított feldarabolt zöldségeket. Ízesítjük sóval őrölt borssal. Lefedve pároljuk, az elpárolgott vizet pótolva. Amikor a zöldségek félig megpuhultak, felengedjük a levesnek megfelelő vízzel. Tovább főzzük, s ha forrni kezd az előkészített húsgombócokat gyorsan beletesszük. Az újraforrástól számítva kb. húsz-huszonöt percig főzzük. Szükség szerint utóízesítjük.')
INSERT INTO RECIPES (id,name,dose_id,recipegroup_id,preparation) VALUES (9506,'Májgombóc leves',1,42,'A májat megmossuk, ledaráljuk. Hozzáadjuk a beáztatott, kicsavart zsemlét. (Ezzel együtt is darálhatjuk.) Ízesítjük sóval, őrölt borssal, apróra vágott petrezselyemmel, valamint egy kevés aprított vöröshagymával. Beletesszük a tojást, és szükség szerint zsemlemorzsát. Alaposan összedolgozzuk, egy tálcára gombócokat formázunk belőle, majd félretesszük.
 Az olajon megpirítjuk a vöröshagyma maradékát, rátesszük a megtisztított feldarabolt zöldségeket. Ízesítjük sóval őrölt borssal. Lefedve pároljuk, az elpárolgott vizet pótolva. Amikor a zöldségek félig megpuhultak, felengedjük a levesnek megfelelő vízzel. Tovább főzzük, s ha forrni kezd az előkészített májgombócokat gyorsan beletesszük. Az újraforrástól számítva kb. húsz-huszonöt percig főzzük. Szükség szerint utóízesítjük.')
INSERT INTO RECIPES (id,name,dose_id,recipegroup_id,preparation) VALUES (9507,'Gulyásleves, zöldséges',1,42,'A húst megmossuk, 2x2 cm-es kockákra vágjuk. A hagymát megtisztítjuk, megmossuk, és felaprózzuk. Az olajat felforrósítjuk, megfonnyasztjuk benne a hagymát, majd lehúzzuk a tűzről, megszórjuk pirospaprikával, rádobjuk a húst, és erős tűzön, folyamatosan kevergetve néhány percig pirítjuk. Hozzáadjuk a lecsót, egy kevés sót és fedő alatt, mérsékelt tűzön, saját levében majdnem puhára pároljuk. Közben meghámozzuk és daraboljuk a zöldségeket, majd valamennyit a húshoz adjuk, és vízzel felengedjük. Fűszerezzük, és fedő alatt, mérsékelt tűzön az egészet puhára főzzük. Petrezselyemmel meghintve tálaljuk.')
INSERT INTO RECIPES (id,name,dose_id,recipegroup_id,preparation) VALUES (9512,'Palócleves',1,42,'A vöröshagymát üvegesre pároljuk az olajon. Rátesszük a megmosott, egyenletes apró kockákra vágott húst. Ízesítjük sóval, őrölt borssal, zúzott fokhagymával. Kétszer-háromszor lepirítjuk, majd vizet aláöntve, fedő alatt pároljuk. Amikor a hús már több mint félig megpuhult, hozzáadjuk a megtisztított, egyenletesre darabolt zöldbabot, és felengedjük a levesnek megfelelő mennyiségű vízzel. Így főzzük tovább. Kis idő múlva beletesszük a megtisztított kis kockákra vágott burgonyát. Amikor az is megpuhult óvatosan hozzákeverjük a lisztből, és tejfölből készített habarást. Kiforraljuk, s ha szükséges utóízesítjük. Amennyiben mélyfagyasztott, vagy konzerv zöldbabot használunk a burgonyával együtt tegyük a levesbe, mivel a főzési ideje mindkettőnek kisebb.')
INSERT INTO RECIPES (id,name,dose_id,recipegroup_id,preparation) VALUES (9513,'Frankfurti leves',1,42,'A kelkáposztát megmossuk, vékony csíkokra vágjuk. Levesnek megfelelő mennyiségű vízben feltesszük főni. Ízesítjük sóval, apróra vágott vöröshagymával, tört fokhagymával, és a többi fűszerrel. Amikor a káposzta félig megpuhult, beletesszük a megtisztított, megmosott, apró kockákra vágott burgonyát és tovább főzzük. Közben az olajból és a lisztből zsemleszínű rántást készítünk, s ha a burgonya is megpuhult besűrítjük a levest. Végül beletesszük a karikákra vágott virslit, és hozzámelegítjük a tejfölt. Néhány percig óvatosan forraljuk.')
INSERT INTO RECIPES (id,name,dose_id,recipegroup_id,preparation) VALUES (9514,'Babgulyás, zöldséges',1,42,'Az apróra vágott vöröshagymát az olajon üvegesre pároljuk. Rátesszük az apró kockákra vágott, megmosott sertéshúst, a szintén felkockázott füstölt sonkát, és a beáztatott, leszűrt szárazbabot. Ízesítjük sóval, majd az elpárolgott vizet pótolva, kétszer-háromszor lepirítjuk. Kevés vizet aláöntve fedő alatt pároljuk. Amikor a víz elpárolgott lepirítjuk, meghintjük liszttel. Később hozzáadjuk a tisztított, megmosott apróra vágott zöldségeket, a zúzott fokhagymát, a petrezselyemlevelet, a fűszerpaprikát és a többi fűszert. Felengedjük kevés vízzel, és kis lángon tovább pároljuk. Amikor már majdnem kész felengedjük a megfelelő mennyiségű vízzel, belerakjuk a kis kockákra vágott burgonyát, és készre főzzük. Szükség szerint utóízesítjük.')
INSERT INTO RECIPES (id,name,dose_id,recipegroup_id,preparation) VALUES (9518,'Sárgaborsó leves, virslivel',1,42,'A sárgaborsót lehetőség szerint átválogatjuk, és szitán keresztül megmossuk. Lecsepegtetjük, majd megfelelő mennyiségű vízben feltesszük főni. Ízesítjük zúzott fokhagymával, egészben hagyott vöröshagymával, babérlevéllel, sóval, és őrölt borssal. Lassú tűznél puhára főzzük. Amikor megpuhult besűrítjük az olajból és lisztből készített, zsemleszínű rántással, amibe belekevertük a fűszerpaprikát. Beletesszük a karikákra vágott virslit és néhány perc alatt, óvatosan kiforraljuk. Végül szükség szerint utóízesítjük.')
INSERT INTO RECIPES (id,name,dose_id,recipegroup_id,preparation) VALUES (3578,'Fejtett bableves, olajjal',1,43,'Az olajon üvegesre pároljuk az apróra vágott hagymát. Rátesszük a megmosott kifejtett babot. Ízesítjük a fűszerekkel, a zúzott fokhagymával, és az apróra vágott petrezselyemmel. Kevés vizet aláöntve pároljuk. Kb. 10 perc múlva hozzáadjuk a megtisztított, megmosott, apróra vágott zöldségeket, és tovább pároljuk. Az elpárolgott vizet pótoljuk, néhányszor átkeverjük. Amikor már majdnem megpuhult, felengedjük a megfelelő mennyiségű vízzel, és tovább főzzük. Végül világos színű rántással sűrítjük, és szükség szerint utóízesítjük.
 Készíthetjük mélyfagyasztottból is, ekkor a főzési idő csökken.')
INSERT INTO RECIPES (id,name,dose_id,recipegroup_id,preparation) VALUES (4588,'Lencsekrémleves',1,43,'A megtisztított vöröshagymát cikkekre vágjuk és a megtisztított, egészben hagyott fokhagymával együtt lábosba tesszük. A szárzeller zsenge leveleit a díszítéshez félretesszük, a többit felaprítjuk és a lábosba tesszük. Felöntjük 2 dl, már kész tyúkhúslevessel, beletesszük a babérlevelet és 20 percig főzzük. Hozzáadjuk a főtt lencsét a levelével együtt és további 5 percig főzzük. A babérlevelet kivesszük, a levest összeturmixoljuk. Előmelegített tányérokba szétosztjuk és 1-1 kanál tejföllel díszítjük. Borssal meghintjük, a félretett zellerlevelekkel díszítve tálaljuk.')
INSERT INTO RECIPES (id,name,dose_id,recipegroup_id,preparation) VALUES (4591,'Zöldbableves kefirrel',1,43,'Az olajon üvegesre pároljuk a vöröshagymát, rátesszük a megtisztított, felaprított zöldségeket. Kevergetve átpirítjuk. Vizet aláöntve fedő alatt pároljuk. Amikor a zöldségek félig megfőttek, fűszerezzük, felengedjük a megfelelő mennyiségű vízzel, és kis lángon tovább főzzük. Amikor minden belevaló megpuhult behabarjuk a kefirben elkevert liszttel. A habarást a tűzről lehúzva, óvatosan végezzük. Végül kevergetés mellett még egyszer felforraljuk. Tálalás előtt amennyiben szükséges, utóízesítjük, illetve kevés petrezselyemzöldet szórunk a tetejére.')
INSERT INTO RECIPES (id,name,dose_id,recipegroup_id,preparation) VALUES (4687,'Sütőtökkrémleves, olajjal',1,43,'A sütőtököt kockára vágjuk. Az olajon átfuttatjuk az apróra vágott vöröshagymát, a zúzott fokhagymát és a gyömbért. Hozzáadjuk a sütőtököt, megszórjuk curry-vel, átkeverjük, majd felengedjük vízzel. Felforraljuk, majd a tököt pürésítjük és a levest szitán átszűrjük.')
INSERT INTO RECIPES (id,name,dose_id,recipegroup_id,preparation) VALUES (4979,'Gyümölcsleves, joghurttal',1,43,'Az almát megmossuk, ha szükséges, megtisztítjuk, a többi gyümölccsel együtt közel azonos méretűre daraboljuk. A levesnek megfelelő mennyiségű a felsorolt fűszerekkel, cukorral ízesített vízben puhára főzzük. Végül óvatosan besűrítjük a joghurtban elkevert liszttel. Kiforraljuk, és néhány csepp citromlével ízesítjük. Lehűtve, tejszínhabbal díszítve tálaljuk.')
INSERT INTO RECIPES (id,name,dose_id,recipegroup_id,preparation) VALUES (9501,'Csontleves',1,43,'A megfelelő méretűre darabolt csontot megmossuk, hideg vízben feltesszük főni. Ügyeljünk rá, hogy megfelelő mennyiségű legyen a víz, mert később a vizet már nem célszerű pótolni, hiszen így könnyen zavarossá válhat a leves. Amikor elkezd forrni a tüzet a legkisebbre vesszük, ízesítjük egészben hagyott hagymával, fokhagymával, szemes borssal. Kb. egy órányi forralás után beletesszük a megtisztított, nagy darabokban hagyott zöldségeket, a sót és a fűszereket. Újraforrástól számítva, még kb. fél órát főzzük, majd félrehúzzuk, illetve lekapcsoljuk, és hagyjuk ülepedni. A levesben főtt zöldséget egyforma darabokra vágjuk, és tálaláskor tesszük a levesbe.')
INSERT INTO RECIPES (id,name,dose_id,recipegroup_id,preparation) VALUES (9541,'Meggyleves',1,43,'A meggyet megmossuk, és levesnek megfelelő mennyiségű vízben feltesszük főni. Ízesítjük a szegfűszeggel, fahéjjal, és a citrom héjával. Kb. tíz perc alatt megfőzzük, majd a tejfölben elkevert liszttel behabarjuk. Óvatosan kiforraljuk, és ízesítjük citromlével illetve a cukorral. Tálalás előtt lehűtjük, a szegfűszeget, fahéjat, és a citromhéjat kiszedjük belőle.
 Használhatunk fagyasztott, vagy befőtt meggyet, ekkor a főzési idő rövidebb.')


INSERT INTO recipe_nutrients (id,recipe_id,NUTRIENTS_ID,QUANTITY) VALUES (1,2016,1,1142.3212)
INSERT INTO recipe_nutrients (id,recipe_id,NUTRIENTS_ID,QUANTITY) VALUES (2,4307,2,114.3212)
INSERT INTO recipe_nutrients (id,recipe_id,NUTRIENTS_ID,QUANTITY) VALUES (3,2016,2,114.3212)








